//
//  EmojiKeywords.swift
//  Pomodoro Timer App
//

import Foundation

/// Maps each emoji to a set of searchable keywords for semantic search.
let emojiKeywords: [String: [String]] = [
    // MARK: - Smileys
    "😀": ["grinning", "happy", "smile", "face", "joy"],
    "😃": ["grinning", "happy", "smile", "eyes", "joy"],
    "😄": ["grinning", "happy", "smile", "laugh", "joy"],
    "😁": ["beaming", "grin", "happy", "smile", "teeth"],
    "😆": ["laughing", "happy", "lol", "haha", "squint"],
    "😅": ["sweat", "nervous", "laugh", "relief", "awkward"],
    "🤣": ["rofl", "laughing", "funny", "lol", "rolling"],
    "😂": ["crying", "laughing", "tears", "joy", "funny", "lol"],
    "🙂": ["smile", "slight", "okay", "fine", "face"],
    "🙃": ["upside", "down", "sarcasm", "irony", "silly"],
    "😉": ["wink", "flirt", "playful", "face"],
    "😊": ["blush", "happy", "smile", "shy", "warm"],
    "😇": ["angel", "halo", "innocent", "good", "holy"],
    "🥰": ["love", "hearts", "adore", "crush", "affection"],
    "😍": ["heart", "eyes", "love", "crush", "adore"],
    "🤩": ["star", "struck", "excited", "amazing", "wow", "starstruck"],
    "😘": ["kiss", "love", "blow", "heart", "flirt"],
    "😗": ["kiss", "whistle", "pucker", "lips"],
    "😚": ["kiss", "blush", "eyes", "closed", "love"],
    "😙": ["kiss", "smile", "happy", "love"],
    "🥲": ["smile", "tear", "sad", "happy", "bittersweet"],
    "😋": ["yummy", "delicious", "food", "tongue", "tasty"],
    "😛": ["tongue", "playful", "silly", "tease"],
    "😜": ["wink", "tongue", "crazy", "silly", "playful"],
    "🤪": ["zany", "crazy", "wild", "silly", "goofy"],
    "😝": ["tongue", "squint", "silly", "gross", "playful"],
    "🤑": ["money", "rich", "dollar", "greedy", "cash"],
    "🤗": ["hug", "hugging", "warm", "embrace", "open"],
    "🤭": ["giggle", "oops", "shy", "cover", "mouth"],
    "🤫": ["shush", "quiet", "secret", "silence", "hush"],
    "🤔": ["thinking", "hmm", "wonder", "consider", "ponder"],
    "🫡": ["salute", "respect", "honor", "military", "yes sir"],
    "🤐": ["zipper", "mouth", "quiet", "secret", "mute", "silent"],
    "🤨": ["raised", "eyebrow", "skeptical", "suspicious", "doubt"],
    "😐": ["neutral", "blank", "expressionless", "meh", "straight"],
    "😑": ["expressionless", "blank", "annoyed", "unamused"],
    "😶": ["silent", "speechless", "no", "mouth", "quiet"],
    "🫥": ["dotted", "invisible", "hidden", "disappear", "fading"],
    "😏": ["smirk", "sly", "flirt", "suggestive", "smug"],
    "😒": ["unamused", "bored", "annoyed", "meh", "displeasure"],
    "🙄": ["eye", "roll", "annoyed", "whatever", "bored"],
    "😬": ["grimace", "awkward", "cringe", "yikes", "nervous"],
    "🤥": ["lying", "pinocchio", "liar", "nose", "fib"],
    "😌": ["relieved", "calm", "peaceful", "content", "serene"],
    "😔": ["pensive", "sad", "thoughtful", "dejected", "down"],
    "😪": ["sleepy", "tired", "drool", "snot", "drowsy"],
    "🤤": ["drool", "hungry", "yummy", "desire", "want"],
    "😴": ["sleep", "zzz", "tired", "snore", "nap", "rest"],
    "😷": ["mask", "sick", "medical", "flu", "covid", "health"],
    "🤒": ["thermometer", "sick", "fever", "ill", "temperature"],
    "🤕": ["bandage", "hurt", "injured", "head", "wound"],
    "🤢": ["nauseous", "sick", "green", "vomit", "ill"],
    "🤮": ["vomit", "sick", "puke", "throw up", "ill"],
    "🥵": ["hot", "sweating", "heat", "warm", "flushed"],
    "🥶": ["cold", "freezing", "ice", "frozen", "chilly"],
    "🥴": ["woozy", "dizzy", "drunk", "tipsy", "disoriented"],
    "😵": ["dizzy", "knocked", "out", "unconscious", "dazed"],
    "🤯": ["mind", "blown", "exploding", "shocked", "amazed"],
    "🤠": ["cowboy", "hat", "western", "yeehaw", "country"],
    "🥳": ["party", "celebrate", "birthday", "confetti", "horn"],
    "🥸": ["disguise", "glasses", "nose", "mustache", "incognito"],
    "😎": ["cool", "sunglasses", "awesome", "confident", "chill"],
    "🤓": ["nerd", "glasses", "geek", "smart", "study"],
    "🧐": ["monocle", "inspect", "curious", "investigate", "fancy"],
    "😕": ["confused", "puzzled", "unsure", "uncertain"],
    "🫤": ["diagonal", "mouth", "skeptical", "unsure", "meh"],
    "😟": ["worried", "concerned", "anxious", "nervous"],
    "🙁": ["frown", "sad", "unhappy", "disappointed"],
    "😮": ["open", "mouth", "surprised", "wow", "shocked"],
    "😯": ["hushed", "surprised", "stunned", "speechless"],
    "😲": ["astonished", "shocked", "amazed", "gasp", "wow"],
    "😳": ["flushed", "embarrassed", "shy", "shocked", "blush"],
    "🥺": ["pleading", "puppy", "eyes", "please", "beg", "cute"],
    "🥹": ["holding", "tears", "emotional", "touched", "grateful"],
    "😦": ["frowning", "open", "mouth", "anguish"],
    "😧": ["anguished", "shocked", "distressed"],
    "😨": ["fearful", "scared", "afraid", "frightened", "terror"],
    "😰": ["anxious", "sweat", "nervous", "worried", "cold"],
    "😥": ["sad", "relieved", "disappointed", "sweat"],
    "😢": ["crying", "sad", "tear", "upset", "weep"],
    "😭": ["sobbing", "crying", "loud", "sad", "wail", "tears"],
    "😱": ["scream", "fear", "horror", "shocked", "terrified"],
    "😖": ["confounded", "frustrated", "annoyed", "upset"],
    "😣": ["persevere", "struggling", "endure", "pain"],
    "😞": ["disappointed", "sad", "let", "down", "dejected"],
    "😓": ["downcast", "sweat", "hard", "work", "tired"],
    "😩": ["weary", "tired", "exhausted", "frustrated", "whiny"],
    "😫": ["tired", "exhausted", "distraught", "fed up"],
    "🥱": ["yawn", "bored", "tired", "sleepy", "boring"],
    "😤": ["steam", "nose", "angry", "frustrated", "huff"],
    "😡": ["angry", "mad", "furious", "rage", "pouting"],
    "😠": ["angry", "mad", "grumpy", "annoyed", "cross"],
    "🤬": ["swearing", "cursing", "angry", "expletive", "mad"],
    "😈": ["devil", "evil", "horns", "mischief", "naughty"],
    "👿": ["imp", "angry", "devil", "evil", "demon"],
    "💀": ["skull", "death", "dead", "skeleton", "spooky"],
    "☠️": ["skull", "crossbones", "death", "danger", "pirate", "poison"],
    "💩": ["poop", "poo", "crap", "funny", "pile"],
    "🤡": ["clown", "funny", "circus", "joke", "fool"],
    "👹": ["ogre", "monster", "demon", "scary", "japanese"],
    "👺": ["goblin", "tengu", "japanese", "mask", "monster"],
    "👻": ["ghost", "halloween", "spooky", "boo", "spirit"],
    "👽": ["alien", "ufo", "space", "extraterrestrial", "et"],
    "👾": ["alien", "monster", "game", "space", "invader", "arcade"],
    "🤖": ["robot", "machine", "android", "bot", "technology"],

    // MARK: - People
    "👋": ["wave", "hello", "hi", "bye", "hand", "greeting"],
    "🤚": ["raised", "back", "hand", "stop", "high five"],
    "🖐️": ["hand", "splayed", "fingers", "five", "stop"],
    "✋": ["raised", "hand", "stop", "high five", "halt"],
    "🖖": ["vulcan", "spock", "star trek", "prosper", "hand"],
    "🫱": ["rightward", "hand", "push", "handshake"],
    "🫲": ["leftward", "hand", "push", "handshake"],
    "🫳": ["palm", "down", "hand", "drop", "lower"],
    "🫴": ["palm", "up", "hand", "offer", "beckon"],
    "👌": ["ok", "okay", "perfect", "fine", "hand", "good"],
    "🤌": ["pinched", "fingers", "italian", "chef", "kiss", "what"],
    "🤏": ["pinching", "small", "tiny", "little", "bit"],
    "✌️": ["peace", "victory", "two", "hand", "sign", "v"],
    "🤞": ["crossed", "fingers", "luck", "hope", "wish"],
    "🫰": ["hand", "index", "thumb", "crossed", "money", "snap"],
    "🤟": ["love", "you", "hand", "rock", "sign"],
    "🤘": ["rock", "metal", "horns", "hand", "sign"],
    "🤙": ["call", "me", "shaka", "hang", "loose", "phone"],
    "👈": ["left", "point", "direction", "hand", "finger"],
    "👉": ["right", "point", "direction", "hand", "finger"],
    "👆": ["up", "point", "direction", "hand", "finger"],
    "🖕": ["middle", "finger", "rude", "flip", "off"],
    "👇": ["down", "point", "direction", "hand", "finger"],
    "☝️": ["up", "point", "index", "one", "hand"],
    "🫵": ["point", "you", "index", "finger", "hand"],
    "👍": ["thumbs", "up", "good", "yes", "like", "approve"],
    "👎": ["thumbs", "down", "bad", "no", "dislike", "disapprove"],
    "✊": ["fist", "raised", "power", "solidarity", "punch"],
    "👊": ["fist", "bump", "punch", "power"],
    "🤛": ["left", "fist", "bump", "punch"],
    "🤜": ["right", "fist", "bump", "punch"],
    "👏": ["clap", "applause", "bravo", "hands", "congrats"],
    "🙌": ["raised", "hands", "celebration", "hooray", "praise"],
    "🫶": ["heart", "hands", "love", "care", "support"],
    "👐": ["open", "hands", "jazz", "hug"],
    "🤲": ["palms", "up", "prayer", "receive", "cupped"],
    "🤝": ["handshake", "deal", "agreement", "partner", "meet"],
    "🙏": ["pray", "please", "thanks", "namaste", "hope", "fold", "hands"],
    "✍️": ["writing", "pen", "hand", "compose", "note", "write"],
    "💅": ["nail", "polish", "manicure", "beauty", "sassy", "fabulous"],
    "🤳": ["selfie", "phone", "camera", "photo"],
    "💪": ["muscle", "strong", "arm", "bicep", "flex", "power", "gym", "workout"],
    "🦾": ["mechanical", "arm", "prosthetic", "robot", "bionic"],
    "🦿": ["mechanical", "leg", "prosthetic", "robot"],
    "🦵": ["leg", "kick", "limb"],
    "🦶": ["foot", "kick", "stomp", "step"],
    "👂": ["ear", "listen", "hear", "sound"],
    "🦻": ["ear", "hearing", "aid", "deaf", "accessibility"],
    "👃": ["nose", "smell", "sniff"],
    "🧠": ["brain", "smart", "think", "mind", "intelligent", "idea", "knowledge"],
    "🫀": ["heart", "organ", "anatomical", "medical"],
    "🫁": ["lungs", "breathe", "organ", "medical"],
    "🦷": ["tooth", "dentist", "dental", "teeth"],
    "🦴": ["bone", "skeleton", "dog"],
    "👀": ["eyes", "look", "see", "watch", "stare", "peek"],
    "👁️": ["eye", "look", "see", "watch"],
    "👅": ["tongue", "taste", "lick", "mouth"],
    "👄": ["lips", "mouth", "kiss"],
    "🫦": ["biting", "lip", "nervous", "flirt", "anxious"],
    "👶": ["baby", "child", "infant", "newborn"],
    "🧒": ["child", "kid", "young", "person"],
    "👦": ["boy", "child", "kid", "male", "young"],
    "👧": ["girl", "child", "kid", "female", "young"],
    "🧑": ["person", "adult", "gender", "neutral"],
    "👱": ["blond", "hair", "person"],
    "👨": ["man", "male", "adult", "guy"],
    "🧔": ["beard", "man", "facial", "hair"],
    "👩": ["woman", "female", "adult", "lady"],
    "🧓": ["older", "person", "elder", "senior"],
    "👴": ["old", "man", "grandpa", "grandfather", "elder"],
    "👵": ["old", "woman", "grandma", "grandmother", "elder"],
    "👮": ["police", "officer", "cop", "law"],
    "🕵️": ["detective", "spy", "investigate", "sleuth"],
    "💂": ["guard", "royal", "british", "soldier"],
    "🥷": ["ninja", "stealth", "hidden", "warrior"],
    "👷": ["construction", "worker", "build", "hard hat", "engineer"],
    "🫅": ["person", "crown", "royal", "monarch"],
    "🤴": ["prince", "royal", "crown", "king"],
    "👸": ["princess", "royal", "crown", "queen", "tiara"],
    "👳": ["turban", "person", "indian"],
    "👲": ["cap", "person", "chinese", "hat"],
    "🧕": ["headscarf", "hijab", "woman", "modest"],
    "🤵": ["tuxedo", "groom", "formal", "suit", "wedding"],
    "👰": ["bride", "wedding", "veil", "marriage"],
    "🤰": ["pregnant", "woman", "baby", "expecting", "mother"],
    "🫃": ["pregnant", "man", "expecting"],
    "🫄": ["pregnant", "person", "expecting"],
    "🤱": ["breastfeeding", "nursing", "baby", "mother"],
    "👼": ["angel", "baby", "cherub", "halo"],
    "🎅": ["santa", "christmas", "claus", "holiday", "xmas"],
    "🤶": ["mrs", "claus", "christmas", "santa", "holiday"],
    "🦸": ["superhero", "hero", "cape", "power", "super"],
    "🦹": ["supervillain", "villain", "evil", "cape"],
    "🧙": ["mage", "wizard", "magic", "sorcerer", "harry potter"],
    "🧚": ["fairy", "magic", "wings", "fantasy"],
    "🧛": ["vampire", "dracula", "blood", "fangs"],
    "🧜": ["mermaid", "merman", "sea", "ocean", "fish"],
    "🧝": ["elf", "fantasy", "lord of the rings", "ears"],
    "🧞": ["genie", "lamp", "wish", "magic", "aladdin"],
    "🧟": ["zombie", "undead", "brain", "walking dead"],
    "🧌": ["troll", "monster", "creature", "fantasy"],
    "💆": ["massage", "spa", "relax", "face"],
    "💇": ["haircut", "salon", "barber", "style"],
    "🚶": ["walking", "pedestrian", "stroll", "person"],
    "🧍": ["standing", "person", "upright"],
    "🧎": ["kneeling", "person", "kneel"],
    "🏃": ["running", "runner", "jog", "sprint", "exercise"],
    "💃": ["dancing", "woman", "salsa", "dancer", "party"],
    "🕺": ["dancing", "man", "disco", "dancer", "party"],
    "👯": ["bunny", "ears", "dancers", "party"],
    "🧖": ["sauna", "steam", "spa", "relax"],
    "🧗": ["climbing", "rock", "climb", "sport"],
    "🤸": ["cartwheel", "gymnastics", "acrobat"],
    "⛹️": ["basketball", "bounce", "dribble", "sport"],
    "🏋️": ["weightlifting", "gym", "strong", "exercise", "lift"],
    "🚴": ["cycling", "bicycle", "bike", "ride", "sport"],
    "🚵": ["mountain", "bike", "cycling", "offroad"],
    "🤼": ["wrestling", "sport", "fight", "grapple"],
    "🤽": ["water", "polo", "swim", "sport"],
    "🤾": ["handball", "sport", "throw"],
    "🤺": ["fencing", "sword", "sport", "duel"],
    "🏇": ["horse", "racing", "jockey", "ride"],
    "⛷️": ["skiing", "ski", "snow", "winter", "sport"],
    "🏂": ["snowboard", "snow", "winter", "sport"],
    "🏌️": ["golf", "club", "sport", "swing"],
    "🏄": ["surfing", "surf", "wave", "ocean", "beach"],
    "🚣": ["rowing", "boat", "row", "water", "canoe"],
    "🏊": ["swimming", "swim", "pool", "water", "sport"],
    "🤿": ["diving", "snorkel", "underwater", "swim", "scuba"],
    "🧘": ["yoga", "meditate", "lotus", "zen", "mindful", "peace", "calm"],

    // MARK: - Animals & Nature
    "🐶": ["dog", "puppy", "pet", "cute", "animal", "woof"],
    "🐱": ["cat", "kitten", "pet", "cute", "animal", "meow"],
    "🐭": ["mouse", "rat", "rodent", "animal", "small"],
    "🐹": ["hamster", "pet", "rodent", "cute", "animal"],
    "🐰": ["rabbit", "bunny", "pet", "easter", "cute"],
    "🦊": ["fox", "animal", "clever", "orange", "wild"],
    "🐻": ["bear", "animal", "teddy", "grizzly", "brown"],
    "🐼": ["panda", "bear", "animal", "china", "bamboo", "cute"],
    "🐻‍❄️": ["polar", "bear", "arctic", "ice", "white", "cold"],
    "🐨": ["koala", "animal", "australia", "cute", "bear"],
    "🐯": ["tiger", "cat", "animal", "wild", "stripe"],
    "🦁": ["lion", "king", "animal", "wild", "mane", "pride"],
    "🐮": ["cow", "moo", "animal", "farm", "dairy"],
    "🐷": ["pig", "animal", "farm", "oink", "pink"],
    "🐽": ["pig", "nose", "snout", "animal"],
    "🐸": ["frog", "toad", "animal", "green", "ribbit"],
    "🐵": ["monkey", "animal", "primate", "ape", "face"],
    "🙈": ["see", "no", "evil", "monkey", "hide", "shy"],
    "🙉": ["hear", "no", "evil", "monkey", "ignore"],
    "🙊": ["speak", "no", "evil", "monkey", "oops", "quiet"],
    "🐒": ["monkey", "primate", "animal", "ape"],
    "🐔": ["chicken", "rooster", "bird", "farm", "hen"],
    "🐧": ["penguin", "bird", "cold", "arctic", "cute", "tuxedo"],
    "🐦": ["bird", "animal", "fly", "tweet", "chirp"],
    "🐤": ["chick", "baby", "bird", "yellow", "cute"],
    "🐣": ["hatching", "chick", "egg", "bird", "baby"],
    "🐥": ["chick", "bird", "baby", "front", "cute"],
    "🦆": ["duck", "bird", "quack", "animal", "water"],
    "🦅": ["eagle", "bird", "america", "freedom", "fly"],
    "🦉": ["owl", "bird", "wise", "night", "hoot"],
    "🦇": ["bat", "animal", "halloween", "vampire", "night"],
    "🐺": ["wolf", "animal", "howl", "wild"],
    "🐗": ["boar", "pig", "wild", "animal"],
    "🐴": ["horse", "animal", "ride", "stable", "pony"],
    "🦄": ["unicorn", "horse", "magic", "fantasy", "rainbow", "mythical"],
    "🐝": ["bee", "honey", "insect", "buzz", "sting", "yellow"],
    "🪱": ["worm", "insect", "earth", "fishing", "crawl"],
    "🐛": ["bug", "insect", "caterpillar", "nature"],
    "🦋": ["butterfly", "insect", "pretty", "nature", "fly", "beautiful"],
    "🐌": ["snail", "slow", "shell", "animal", "slug"],
    "🐞": ["ladybug", "insect", "bug", "luck", "red"],
    "🐜": ["ant", "insect", "bug", "small", "colony"],
    "🪰": ["fly", "insect", "bug", "pest"],
    "🪲": ["beetle", "insect", "bug"],
    "🪳": ["cockroach", "insect", "bug", "pest"],
    "🦟": ["mosquito", "insect", "bug", "bite"],
    "🦗": ["cricket", "insect", "chirp", "grasshopper"],
    "🕷️": ["spider", "web", "insect", "creepy", "arachnid"],
    "🦂": ["scorpion", "zodiac", "sting", "desert"],
    "🐢": ["turtle", "tortoise", "slow", "animal", "shell"],
    "🐍": ["snake", "serpent", "reptile", "slither"],
    "🦎": ["lizard", "reptile", "gecko", "animal"],
    "🦖": ["dinosaur", "trex", "tyrannosaurus", "fossil", "jurassic"],
    "🦕": ["dinosaur", "sauropod", "brontosaurus", "fossil", "jurassic"],
    "🐙": ["octopus", "sea", "tentacle", "ocean", "squid"],
    "🦑": ["squid", "sea", "ocean", "tentacle"],
    "🦐": ["shrimp", "prawn", "seafood", "ocean"],
    "🦞": ["lobster", "seafood", "ocean", "claw"],
    "🦀": ["crab", "seafood", "ocean", "claw", "zodiac"],
    "🐡": ["blowfish", "puffer", "fish", "ocean"],
    "🐠": ["fish", "tropical", "ocean", "nemo"],
    "🐟": ["fish", "ocean", "sea", "animal", "swim"],
    "🐬": ["dolphin", "ocean", "sea", "smart", "swim", "flipper"],
    "🐳": ["whale", "ocean", "sea", "spout", "spray", "water"],
    "🐋": ["whale", "ocean", "sea", "blue", "humpback"],
    "🦈": ["shark", "ocean", "dangerous", "jaws", "fish"],
    "🦭": ["seal", "ocean", "sea", "animal", "cute"],
    "🐊": ["crocodile", "alligator", "reptile", "dangerous"],
    "🐅": ["tiger", "cat", "wild", "stripe", "animal"],
    "🐆": ["leopard", "cheetah", "cat", "wild", "spots"],
    "🦓": ["zebra", "stripe", "animal", "africa", "horse"],
    "🦍": ["gorilla", "ape", "monkey", "strong", "primate"],
    "🦧": ["orangutan", "ape", "monkey", "primate"],
    "🦣": ["mammoth", "elephant", "prehistoric", "ice age", "tusk"],
    "🐘": ["elephant", "animal", "big", "trunk", "africa", "memory"],
    "🦛": ["hippo", "hippopotamus", "animal", "africa"],
    "🦏": ["rhinoceros", "rhino", "horn", "animal", "africa"],
    "🐪": ["camel", "desert", "hump", "one", "animal"],
    "🐫": ["camel", "desert", "hump", "two", "animal"],
    "🦒": ["giraffe", "animal", "tall", "neck", "africa", "spots"],
    "🦘": ["kangaroo", "australia", "hop", "joey", "pouch"],
    "🦬": ["bison", "buffalo", "animal", "american"],
    "🐃": ["water", "buffalo", "animal", "ox"],
    "🐂": ["ox", "bull", "animal", "strong"],
    "🐄": ["cow", "animal", "farm", "dairy", "moo", "milk"],
    "🐎": ["horse", "racing", "gallop", "ride", "animal"],
    "🐖": ["pig", "animal", "farm", "pork"],
    "🐏": ["ram", "sheep", "animal", "zodiac"],
    "🐑": ["sheep", "lamb", "animal", "wool", "farm"],
    "🦙": ["llama", "alpaca", "animal", "south america"],
    "🐐": ["goat", "animal", "greatest", "zodiac"],
    "🦌": ["deer", "animal", "bambi", "antler", "stag"],
    "🐕": ["dog", "pet", "animal", "companion"],
    "🐩": ["poodle", "dog", "fancy", "pet"],
    "🦮": ["guide", "dog", "blind", "service"],
    "🐕‍🦺": ["service", "dog", "vest", "assistance"],
    "🐈": ["cat", "pet", "animal", "feline"],
    "🐈‍⬛": ["black", "cat", "halloween", "superstition"],
    "🪶": ["feather", "bird", "quill", "write", "light"],
    "🐓": ["rooster", "chicken", "cock", "farm", "dawn", "morning"],
    "🦃": ["turkey", "thanksgiving", "bird", "gobble"],
    "🦤": ["dodo", "bird", "extinct", "gone"],
    "🦚": ["peacock", "bird", "feather", "beautiful", "colorful"],
    "🦜": ["parrot", "bird", "tropical", "talk", "colorful"],
    "🦢": ["swan", "bird", "elegant", "graceful", "lake"],
    "🦩": ["flamingo", "bird", "pink", "tropical"],
    "🕊️": ["dove", "peace", "bird", "white", "olive"],
    "🐇": ["rabbit", "bunny", "animal", "fast", "hop"],
    "🦝": ["raccoon", "animal", "trash", "panda", "mask"],
    "🦨": ["skunk", "animal", "stink", "smell"],
    "🦡": ["badger", "animal", "burrow"],
    "🦫": ["beaver", "animal", "dam", "wood", "build"],
    "🦦": ["otter", "animal", "cute", "water", "swim"],
    "🦥": ["sloth", "animal", "slow", "lazy", "hang"],
    "🐁": ["mouse", "small", "rodent", "animal"],
    "🐀": ["rat", "rodent", "animal"],
    "🐿️": ["chipmunk", "squirrel", "animal", "nut", "acorn"],
    "🦔": ["hedgehog", "animal", "spiny", "cute", "sonic"],
    "🌵": ["cactus", "desert", "plant", "prickly", "succulent"],
    "🎄": ["christmas", "tree", "holiday", "xmas", "evergreen", "decoration"],
    "🌲": ["evergreen", "tree", "pine", "forest", "nature"],
    "🌳": ["tree", "deciduous", "oak", "nature", "forest"],
    "🌴": ["palm", "tree", "tropical", "beach", "vacation", "island"],
    "🪵": ["wood", "log", "lumber", "timber"],
    "🌱": ["seedling", "plant", "grow", "sprout", "nature", "new"],
    "🌿": ["herb", "plant", "leaf", "green", "nature"],
    "☘️": ["shamrock", "clover", "irish", "ireland", "green"],
    "🍀": ["four", "leaf", "clover", "lucky", "luck", "irish"],
    "🎍": ["bamboo", "japanese", "pine", "new year"],
    "🪴": ["potted", "plant", "house", "indoor", "garden"],
    "🎋": ["tanabata", "tree", "japanese", "wish"],
    "🍃": ["leaf", "wind", "nature", "green", "blowing"],
    "🍂": ["fallen", "leaf", "autumn", "fall", "season"],
    "🍁": ["maple", "leaf", "canada", "fall", "autumn", "red"],
    "🪺": ["nest", "eggs", "bird", "spring"],
    "🪹": ["nest", "empty", "bird"],
    "🍄": ["mushroom", "fungus", "toadstool", "nature", "mario"],
    "🌾": ["rice", "sheaf", "harvest", "grain", "wheat", "farm"],
    "💐": ["bouquet", "flowers", "gift", "romantic", "arrangement"],
    "🌷": ["tulip", "flower", "spring", "pink", "garden"],
    "🌹": ["rose", "flower", "love", "romantic", "red", "valentine"],
    "🥀": ["wilted", "flower", "dead", "sad", "faded"],
    "🌺": ["hibiscus", "flower", "tropical", "hawaii"],
    "🌸": ["cherry", "blossom", "flower", "spring", "japan", "sakura", "pink"],
    "🌼": ["blossom", "flower", "nature", "bloom", "yellow"],
    "🌻": ["sunflower", "flower", "sun", "yellow", "happy", "summer"],
    "🌞": ["sun", "face", "sunny", "bright", "happy", "morning"],
    "🌝": ["moon", "face", "full", "night", "creepy"],
    "🌛": ["moon", "first", "quarter", "face", "night"],
    "🌜": ["moon", "last", "quarter", "face", "night"],
    "🌚": ["moon", "new", "face", "dark", "night", "creepy"],
    "🌕": ["full", "moon", "night", "bright"],
    "🌙": ["crescent", "moon", "night", "sleep", "dream"],
    "🌎": ["earth", "globe", "world", "america", "planet"],
    "🌍": ["earth", "globe", "world", "africa", "europe", "planet"],
    "🌏": ["earth", "globe", "world", "asia", "australia", "planet"],
    "🪐": ["saturn", "planet", "ring", "space", "astronomy"],
    "💫": ["dizzy", "star", "sparkle", "shooting"],
    "⭐": ["star", "gold", "favorite", "rating", "bookmark"],
    "🌟": ["glowing", "star", "sparkle", "shine", "bright"],
    "✨": ["sparkles", "magic", "clean", "shiny", "new", "glitter"],
    "⚡": ["lightning", "bolt", "electric", "power", "zap", "energy", "thunder", "fast", "quick", "speed"],
    "☄️": ["comet", "space", "shooting", "star", "meteor"],
    "💥": ["boom", "explosion", "crash", "bang", "collision"],
    "🔥": ["fire", "hot", "flame", "lit", "burn", "trending"],
    "🌪️": ["tornado", "wind", "storm", "twister"],
    "🌈": ["rainbow", "colorful", "pride", "luck", "weather"],
    "☀️": ["sun", "sunny", "bright", "weather", "warm", "hot", "summer"],
    "🌊": ["wave", "ocean", "sea", "water", "surf", "beach", "tsunami"],

    // MARK: - Food & Drink
    "🍏": ["apple", "green", "fruit", "healthy"],
    "🍎": ["apple", "red", "fruit", "healthy", "teacher"],
    "🍐": ["pear", "fruit", "green"],
    "🍊": ["orange", "tangerine", "fruit", "citrus"],
    "🍋": ["lemon", "citrus", "fruit", "yellow", "sour"],
    "🍌": ["banana", "fruit", "yellow", "monkey"],
    "🍉": ["watermelon", "fruit", "summer", "juicy", "red"],
    "🍇": ["grapes", "fruit", "wine", "purple"],
    "🍓": ["strawberry", "fruit", "berry", "red", "sweet"],
    "🫐": ["blueberry", "berry", "fruit", "blue"],
    "🍒": ["cherry", "cherries", "fruit", "red"],
    "🍑": ["peach", "fruit", "fuzzy", "butt"],
    "🥭": ["mango", "fruit", "tropical", "sweet"],
    "🍍": ["pineapple", "fruit", "tropical", "sweet"],
    "🥥": ["coconut", "tropical", "palm", "fruit"],
    "🥝": ["kiwi", "fruit", "green", "fuzzy"],
    "🍅": ["tomato", "vegetable", "red", "fruit"],
    "🍆": ["eggplant", "aubergine", "vegetable", "purple"],
    "🥑": ["avocado", "fruit", "green", "guacamole", "toast"],
    "🥦": ["broccoli", "vegetable", "green", "healthy"],
    "🌶️": ["pepper", "hot", "chili", "spicy", "red"],
    "🌽": ["corn", "maize", "vegetable", "cob"],
    "🥕": ["carrot", "vegetable", "orange", "rabbit"],
    "🥔": ["potato", "vegetable", "spud", "fries"],
    "🍞": ["bread", "loaf", "toast", "bakery"],
    "🥐": ["croissant", "bread", "french", "pastry", "breakfast"],
    "🧇": ["waffle", "breakfast", "grid"],
    "🥞": ["pancake", "breakfast", "stack", "syrup"],
    "🍳": ["egg", "fried", "cooking", "breakfast", "pan"],
    "🥓": ["bacon", "meat", "pork", "breakfast", "crispy"],
    "🥩": ["steak", "meat", "beef", "cut", "raw"],
    "🍗": ["drumstick", "chicken", "poultry", "leg", "meat"],
    "🍖": ["meat", "bone", "rib", "bbq"],
    "🌭": ["hot dog", "sausage", "frankfurter", "mustard"],
    "🍔": ["hamburger", "burger", "fast food", "beef", "cheeseburger"],
    "🍟": ["french fries", "fries", "chips", "fast food", "potato"],
    "🍕": ["pizza", "slice", "cheese", "italian", "pepperoni"],
    "🥪": ["sandwich", "bread", "lunch", "sub", "deli"],
    "🥙": ["pita", "falafel", "stuffed", "wrap", "kebab"],
    "🌮": ["taco", "mexican", "food", "shell", "tuesday"],
    "🌯": ["burrito", "mexican", "wrap", "food"],
    "🥗": ["salad", "healthy", "green", "bowl", "vegetable"],
    "🍝": ["spaghetti", "pasta", "italian", "noodle"],
    "🍜": ["ramen", "noodle", "soup", "bowl", "japanese"],
    "🍲": ["stew", "pot", "soup", "curry", "hot"],
    "🍛": ["curry", "rice", "indian", "food"],
    "🍣": ["sushi", "japanese", "fish", "rice", "raw"],
    "🍱": ["bento", "box", "japanese", "lunch", "meal"],
    "🥟": ["dumpling", "gyoza", "dim sum", "chinese"],
    "🍤": ["shrimp", "tempura", "fried", "seafood"],
    "🍙": ["rice", "ball", "onigiri", "japanese"],
    "🍚": ["rice", "bowl", "white", "grain"],
    "🍘": ["rice", "cracker", "japanese", "snack"],
    "🍧": ["shaved", "ice", "dessert", "cold", "sweet"],
    "🍨": ["ice cream", "dessert", "sundae", "sweet", "cold"],
    "🍦": ["ice cream", "cone", "soft serve", "dessert", "sweet"],
    "🥧": ["pie", "dessert", "baked", "slice"],
    "🧁": ["cupcake", "muffin", "dessert", "sweet", "frosting"],
    "🍰": ["cake", "shortcake", "dessert", "sweet", "slice", "strawberry"],
    "🎂": ["birthday", "cake", "celebrate", "candles", "party"],
    "🍮": ["custard", "pudding", "flan", "dessert"],
    "🍭": ["lollipop", "candy", "sweet", "sugar"],
    "🍬": ["candy", "sweet", "wrapper", "sugar"],
    "🍫": ["chocolate", "bar", "candy", "sweet", "cocoa"],
    "🍿": ["popcorn", "movie", "cinema", "snack", "theater"],
    "🍩": ["donut", "doughnut", "dessert", "sweet", "sprinkle"],
    "🍪": ["cookie", "biscuit", "sweet", "snack", "baked", "chocolate chip"],
    "🥜": ["peanut", "nut", "snack", "legume"],
    "🍯": ["honey", "pot", "sweet", "bear", "bee"],
    "🥛": ["milk", "glass", "drink", "dairy", "white"],
    "🍼": ["baby", "bottle", "milk", "infant", "formula"],
    "🫖": ["teapot", "tea", "pour", "kettle"],
    "☕": ["coffee", "hot", "drink", "tea", "cafe", "mug", "cup", "morning", "espresso", "latte", "cappuccino"],
    "🍵": ["tea", "green", "matcha", "cup", "drink", "japanese"],
    "🧃": ["juice", "box", "drink", "straw", "kid"],
    "🥤": ["cup", "straw", "drink", "soda", "takeout"],
    "🧋": ["boba", "bubble", "tea", "milk tea", "tapioca"],
    "🍶": ["sake", "japanese", "drink", "alcohol", "rice wine"],
    "🍺": ["beer", "drink", "alcohol", "mug", "pub", "cheers"],
    "🍻": ["beers", "cheers", "drink", "toast", "celebrate", "clink"],
    "🥂": ["champagne", "cheers", "toast", "celebrate", "wine", "sparkling"],
    "🍷": ["wine", "glass", "red", "drink", "alcohol"],
    "🥃": ["whiskey", "tumbler", "glass", "drink", "bourbon", "scotch"],
    "🍸": ["cocktail", "martini", "drink", "bar", "alcohol"],
    "🍹": ["tropical", "drink", "cocktail", "umbrella", "vacation"],
    "🍾": ["champagne", "bottle", "celebrate", "pop", "party"],

    // MARK: - Activities
    "⚽": ["soccer", "football", "ball", "sport", "kick"],
    "🏀": ["basketball", "ball", "sport", "hoop", "nba"],
    "🏈": ["football", "american", "sport", "nfl", "ball"],
    "⚾": ["baseball", "ball", "sport", "mlb"],
    "🥎": ["softball", "ball", "sport"],
    "🎾": ["tennis", "ball", "sport", "racket"],
    "🏐": ["volleyball", "ball", "sport", "beach"],
    "🏉": ["rugby", "ball", "sport", "football"],
    "🎱": ["billiards", "pool", "8 ball", "eight", "game"],
    "🏓": ["ping", "pong", "table tennis", "sport", "paddle"],
    "🏸": ["badminton", "shuttlecock", "sport", "racket"],
    "🏒": ["ice", "hockey", "sport", "stick", "puck"],
    "🏑": ["field", "hockey", "sport", "stick"],
    "🏏": ["cricket", "sport", "bat", "ball"],
    "⛳": ["golf", "flag", "hole", "sport", "course"],
    "🏹": ["bow", "arrow", "archery", "sport", "target"],
    "🎣": ["fishing", "rod", "fish", "pole", "hook"],
    "🥊": ["boxing", "glove", "fight", "sport", "punch"],
    "🥋": ["martial", "arts", "karate", "judo", "taekwondo", "gi"],
    "🎽": ["running", "shirt", "jersey", "sport", "sash"],
    "🛹": ["skateboard", "skate", "sport", "trick"],
    "🛼": ["roller", "skate", "skating", "sport"],
    "⛸️": ["ice", "skating", "figure", "rink", "winter"],
    "🎿": ["ski", "skiing", "snow", "winter", "sport"],
    "🏆": ["trophy", "winner", "champion", "gold", "prize", "award", "best", "first"],
    "🥇": ["gold", "medal", "first", "winner", "champion"],
    "🥈": ["silver", "medal", "second", "place"],
    "🥉": ["bronze", "medal", "third", "place"],
    "🏅": ["medal", "sports", "award", "achievement"],
    "🎪": ["circus", "tent", "carnival", "show"],
    "🤹": ["juggling", "circus", "skill", "balls"],
    "🎭": ["theater", "drama", "performing", "arts", "mask", "comedy", "tragedy"],
    "🩰": ["ballet", "dance", "shoes", "pointe"],
    "🎨": ["art", "paint", "palette", "creative", "draw", "artist", "color"],
    "🎬": ["movie", "film", "cinema", "action", "clapper", "hollywood"],
    "🎤": ["microphone", "sing", "karaoke", "music", "voice", "mic"],
    "🎧": ["headphones", "music", "listen", "audio", "headset"],
    "🎼": ["music", "score", "notes", "sheet", "treble"],
    "🎹": ["piano", "keyboard", "music", "keys", "instrument"],
    "🥁": ["drum", "music", "beat", "instrument", "percussion"],
    "🎷": ["saxophone", "sax", "music", "jazz", "instrument"],
    "🎺": ["trumpet", "music", "horn", "brass", "instrument"],
    "🎸": ["guitar", "music", "rock", "electric", "instrument", "acoustic"],
    "🪕": ["banjo", "music", "country", "instrument", "string"],
    "🎻": ["violin", "music", "fiddle", "classical", "instrument", "string"],
    "🎲": ["dice", "game", "gamble", "random", "luck", "casino"],
    "♟️": ["chess", "pawn", "game", "strategy", "board"],
    "🎯": ["target", "bullseye", "dart", "aim", "goal", "direct hit"],
    "🎳": ["bowling", "pins", "ball", "sport", "strike"],
    "🎮": ["game", "controller", "video", "gaming", "play", "console", "joystick"],
    "🕹️": ["joystick", "game", "arcade", "retro", "play"],
    "🧩": ["puzzle", "piece", "jigsaw", "game", "fit"],
    "🪩": ["disco", "ball", "mirror", "dance", "party", "club"],

    // MARK: - Travel & Places
    "🚗": ["car", "automobile", "drive", "vehicle", "red"],
    "🚕": ["taxi", "cab", "car", "ride", "yellow"],
    "🚙": ["suv", "car", "vehicle", "sport", "utility"],
    "🚌": ["bus", "transit", "vehicle", "public", "transport"],
    "🏎️": ["race", "car", "fast", "formula", "speed", "racing"],
    "🚓": ["police", "car", "cop", "patrol", "emergency"],
    "🚑": ["ambulance", "emergency", "hospital", "medical"],
    "🚒": ["fire", "truck", "engine", "emergency"],
    "🚐": ["minibus", "van", "vehicle", "transport"],
    "🛻": ["pickup", "truck", "vehicle"],
    "🚚": ["truck", "delivery", "moving", "vehicle"],
    "🚜": ["tractor", "farm", "vehicle", "agriculture"],
    "🛵": ["scooter", "motor", "vespa", "vehicle"],
    "🏍️": ["motorcycle", "bike", "motorbike", "vehicle", "harley"],
    "🚲": ["bicycle", "bike", "cycle", "ride", "pedal"],
    "🚁": ["helicopter", "chopper", "fly", "aviation"],
    "🛸": ["ufo", "flying", "saucer", "alien", "spaceship"],
    "🚀": ["rocket", "space", "launch", "fast", "spaceship", "nasa", "takeoff"],
    "✈️": ["airplane", "plane", "fly", "travel", "flight", "aviation"],
    "💺": ["seat", "airplane", "chair", "flight"],
    "🚂": ["train", "locomotive", "steam", "railway"],
    "🚄": ["train", "high", "speed", "bullet", "shinkansen", "fast"],
    "🚇": ["metro", "subway", "train", "underground", "transit"],
    "⛵": ["sailboat", "boat", "sailing", "wind", "sea"],
    "🚢": ["ship", "cruise", "boat", "ocean", "vessel"],
    "🏖️": ["beach", "umbrella", "sand", "vacation", "summer", "sun"],
    "🏝️": ["island", "desert", "tropical", "palm", "vacation"],
    "🏜️": ["desert", "sand", "dry", "hot"],
    "🌋": ["volcano", "eruption", "lava", "mountain"],
    "⛰️": ["mountain", "peak", "summit", "nature"],
    "🏔️": ["mountain", "snow", "capped", "peak"],
    "🏕️": ["camping", "tent", "outdoors", "nature", "campsite"],
    "🏠": ["house", "home", "building", "residence"],
    "🏡": ["house", "garden", "home", "yard"],
    "🏢": ["office", "building", "work", "business", "corporate"],
    "🏥": ["hospital", "medical", "health", "doctor", "emergency"],
    "🏫": ["school", "education", "learning", "building"],
    "🏛️": ["classical", "building", "museum", "government", "bank"],
    "⛪": ["church", "religion", "christian", "worship"],
    "🕌": ["mosque", "islam", "muslim", "worship"],
    "🌅": ["sunrise", "morning", "dawn", "beach", "beautiful"],
    "🌄": ["sunrise", "mountain", "morning", "dawn"],
    "🌇": ["sunset", "city", "evening", "dusk", "buildings"],
    "🌆": ["cityscape", "dusk", "evening", "skyline", "buildings"],
    "🏙️": ["cityscape", "city", "skyline", "urban", "buildings"],
    "🌃": ["night", "city", "stars", "starry", "urban"],
    "🌌": ["milky", "way", "galaxy", "space", "stars", "night"],
    "🌉": ["bridge", "night", "city", "golden gate"],

    // MARK: - Objects
    "⌚": ["watch", "time", "wrist", "clock", "accessory"],
    "📱": ["phone", "mobile", "iphone", "cell", "smartphone"],
    "💻": ["laptop", "computer", "mac", "work", "coding", "programming"],
    "⌨️": ["keyboard", "type", "computer", "input"],
    "🖥️": ["desktop", "computer", "monitor", "screen", "display"],
    "🖨️": ["printer", "print", "paper", "office"],
    "📷": ["camera", "photo", "picture", "photography"],
    "🎥": ["movie", "camera", "film", "video", "record"],
    "📺": ["television", "tv", "screen", "watch", "show"],
    "📻": ["radio", "music", "broadcast", "fm", "am"],
    "⏰": ["alarm", "clock", "time", "wake", "morning"],
    "⌛": ["hourglass", "time", "sand", "wait", "timer"],
    "⏳": ["hourglass", "time", "flowing", "sand", "running"],
    "💡": ["light", "bulb", "idea", "bright", "lamp", "creative"],
    "🔋": ["battery", "power", "charge", "energy"],
    "🔌": ["plug", "electric", "power", "outlet", "charge"],
    "💰": ["money", "bag", "dollar", "rich", "cash", "wealth"],
    "💵": ["dollar", "money", "bill", "cash", "usd"],
    "💳": ["credit", "card", "payment", "bank", "money", "debit"],
    "💎": ["gem", "diamond", "jewel", "precious", "sparkle"],
    "🔧": ["wrench", "tool", "fix", "repair", "mechanic"],
    "🔨": ["hammer", "tool", "build", "construction", "nail"],
    "🔩": ["nut", "bolt", "screw", "tool", "hardware"],
    "⚙️": ["gear", "settings", "cog", "mechanical", "config"],
    "🔫": ["gun", "water", "pistol", "squirt", "toy"],
    "🔮": ["crystal", "ball", "magic", "fortune", "predict", "future"],
    "🔭": ["telescope", "astronomy", "space", "stars", "look"],
    "🔬": ["microscope", "science", "lab", "research", "biology"],
    "💊": ["pill", "medicine", "drug", "pharmacy", "health"],
    "💉": ["syringe", "needle", "vaccine", "injection", "medical"],
    "🧬": ["dna", "gene", "science", "biology", "helix"],
    "📚": ["books", "read", "study", "library", "education", "learn", "literature", "knowledge", "school"],
    "📖": ["book", "open", "read", "study", "page"],
    "📕": ["book", "red", "closed", "read"],
    "📗": ["book", "green", "read"],
    "📘": ["book", "blue", "read"],
    "📝": ["memo", "note", "write", "pencil", "paper", "draft"],
    "📅": ["calendar", "date", "schedule", "plan", "event"],
    "📊": ["chart", "bar", "graph", "statistics", "data", "analytics"],
    "📈": ["chart", "increase", "up", "growth", "trending", "stock"],
    "📉": ["chart", "decrease", "down", "loss", "decline"],
    "📋": ["clipboard", "list", "checklist", "task", "assignment"],
    "📌": ["pin", "pushpin", "location", "mark", "important"],
    "📎": ["paperclip", "clip", "attachment", "office"],
    "✂️": ["scissors", "cut", "trim", "craft"],
    "🔒": ["lock", "locked", "security", "private", "closed"],
    "🔓": ["unlock", "unlocked", "open", "security"],
    "🔑": ["key", "lock", "password", "access", "unlock"],

    // MARK: - Symbols
    "❤️": ["heart", "red", "love", "like", "valentine"],
    "🧡": ["heart", "orange", "love"],
    "💛": ["heart", "yellow", "love", "friendship"],
    "💚": ["heart", "green", "love", "jealousy"],
    "💙": ["heart", "blue", "love", "trust"],
    "💜": ["heart", "purple", "love"],
    "🖤": ["heart", "black", "love", "dark", "emo"],
    "🤍": ["heart", "white", "love", "pure"],
    "🤎": ["heart", "brown", "love"],
    "💔": ["broken", "heart", "sad", "heartbreak", "pain"],
    "❤️‍🔥": ["heart", "fire", "passion", "burning", "love"],
    "💕": ["hearts", "two", "love", "affection"],
    "💞": ["hearts", "revolving", "love", "cute"],
    "💓": ["heart", "beating", "love", "pulse", "alive"],
    "💗": ["heart", "growing", "love", "pink"],
    "💖": ["heart", "sparkle", "love", "fancy"],
    "💘": ["heart", "arrow", "cupid", "love", "valentine"],
    "💝": ["heart", "ribbon", "gift", "love", "valentine"],
    "💟": ["heart", "decoration", "love"],
    "☮️": ["peace", "sign", "symbol", "hippie"],
    "♻️": ["recycle", "green", "environment", "eco", "sustainability"],
    "✅": ["check", "mark", "done", "complete", "yes", "correct", "green"],
    "❌": ["cross", "mark", "wrong", "no", "error", "delete", "red"],
    "❗": ["exclamation", "warning", "important", "alert", "attention"],
    "❓": ["question", "mark", "what", "help", "confused"],
    "⚠️": ["warning", "caution", "alert", "danger", "attention"],
    "💯": ["hundred", "perfect", "score", "percent", "100"],
    "💤": ["sleep", "zzz", "tired", "snore", "rest", "nap"],
    "🎵": ["music", "note", "song", "melody", "tune"],
    "🎶": ["music", "notes", "song", "melody", "singing"],
    "✔️": ["check", "mark", "done", "correct", "yes", "tick"],
    "🔴": ["red", "circle", "dot", "stop", "record"],
    "🟠": ["orange", "circle", "dot"],
    "🟡": ["yellow", "circle", "dot"],
    "🟢": ["green", "circle", "dot", "go"],
    "🔵": ["blue", "circle", "dot"],
    "🟣": ["purple", "circle", "dot"],
    "⚫": ["black", "circle", "dot"],
    "⚪": ["white", "circle", "dot"],

    // MARK: - Flags
    "🏁": ["checkered", "flag", "race", "finish", "racing"],
    "🚩": ["red", "flag", "warning", "triangular"],
    "🎌": ["crossed", "flags", "japanese", "celebration"],
    "🏴": ["black", "flag"],
    "🏳️": ["white", "flag", "surrender", "peace"],
    "🏳️‍🌈": ["rainbow", "pride", "lgbtq", "flag", "gay"],
    "🏳️‍⚧️": ["transgender", "pride", "flag", "trans"],
    "🏴‍☠️": ["pirate", "flag", "skull", "jolly roger"],
    "🇺🇸": ["usa", "america", "united states", "flag", "american"],
    "🇬🇧": ["uk", "britain", "united kingdom", "flag", "british", "england"],
    "🇨🇦": ["canada", "flag", "canadian", "maple"],
    "🇦🇺": ["australia", "flag", "australian", "aussie"],
    "🇫🇷": ["france", "flag", "french"],
    "🇩🇪": ["germany", "flag", "german", "deutsch"],
    "🇮🇹": ["italy", "flag", "italian"],
    "🇪🇸": ["spain", "flag", "spanish"],
    "🇯🇵": ["japan", "flag", "japanese"],
    "🇰🇷": ["korea", "south", "flag", "korean"],
    "🇨🇳": ["china", "flag", "chinese"],
    "🇮🇳": ["india", "flag", "indian"],
    "🇧🇷": ["brazil", "flag", "brazilian"],
    "🇲🇽": ["mexico", "flag", "mexican"],
]
